DrinkDatabase/Models/Drink.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DrinkDatabase.Models
{
    public class Drink
    {
        [Key]
        public int ID { get; set; }
        [StringLength(128, MinimumLength=3)]
        public string Name { get; set; }
        public string Instructions { get; set; }
        [StringLength(128, MinimumLength = 3)]
        public string Glass { get; set; }
        public string Notes { get; set; }

        public virtual ICollection<DrinkIngredient> DrinkIngredients { get; set; }
    }
}

DrinkDatabase/Controllers/DrinkController.cs
using DrinkDatabase.Models;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure.AdamExtension;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DrinkDatabase.Controllers
{
    [Authorize]
    public class DrinkController : Controller
    {
        private IAppDBContext db;

        /// <summary>
        /// normal constructor - used for normal runtime.
        /// </summary>
        public DrinkController()
        {
            db = new ApplicationDbContext();
        }
        /// <summary>
        /// Abnormal constructor. Used for tests. Give it your own <param name="DBC">database context</param>, e.g., a test.
        /// </summary>
        public DrinkController(IAppDBContext DBC)
        {
            db = DBC;
        }
        // GET: Drink
        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            return View(await db.Query<Drink>().ToListAsync());
        }

        // GET: Drink/Details/5
        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drink drink = await db.Query<Drink>().Include(d => d.DrinkIngredients).Where(d => d.ID == id).SingleAsync();
            if (drink == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.DrinkIngredients = drink.DrinkIngredients;
            return View(drink);
        }

        // GET: Drink/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Drink/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Name,Instructions,Glass,Notes")] Drink drink)
        {
            if (ModelState.IsValid)
            {
                db.Add(drink);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(drink);
        }

        // GET: Drink/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drink drinkToUpdate = await db.Query<Drink>()
                .Include(d => d.DrinkIngredients)
                .Where(d => d.ID == id)
                .SingleAsync();
            if (drinkToUpdate == null)
            {
                return HttpNotFound();
            }
            if (drinkToUpdate.DrinkIngredients == null)
            {
                drinkToUpdate.DrinkIngredients = new HashSet<DrinkIngredient>();
            }
            ViewBag.DrinkIngredients = drinkToUpdate.DrinkIngredients;
            return View(drinkToUpdate);
        }

        // POST: Drink/Edit/n
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Name,Instructions,Glass,Notes")] Drink drink,
            [Bind(Include= "ID,Amount,Brand,IngredientID,DrinkID")] IEnumerable<DrinkIngredient> DrinkIngredients)
        {
            if (ModelState.IsValid)
            {
                var whichToDelete = Request.Form.AllKeys.Where(s => s.Contains("DeleteDrinkIngredients["));
                List<int> deletionList = new List<int>();
                foreach (var s in whichToDelete)
                {
                    var firstBracket = s.IndexOf('[') + 1;
                    int thisIndex;
                    if (int.TryParse(s.Substring(firstBracket, s.IndexOf(']', firstBracket) - firstBracket), out thisIndex))
                    {
                        if(Request.Form[s] == "on")
                            deletionList.Add(thisIndex);
                    }
                }

                db.Entry(drink).State = EntityState.Modified;
                if (DrinkIngredients != null)
                {
                    foreach (var item in DrinkIngredients)
                    {
                        if(deletionList.Contains(item.ID))
                        {
                            drink.DrinkIngredients.Remove(item);
                            db.Entry(item).State = EntityState.Deleted;
                        }
                        else
                        {
                            db.Entry(item).State = EntityState.Modified;
                        }
                    }
                }
                await db.SaveChangesAsync();


                if (Request.IsAjaxRequest())
                {
                    ViewBag.DrinkIngredients = drink.DrinkIngredients;
                    return PartialView("_EditableDrink", drink);
                }
                return RedirectToAction("Index");
            }
            return View(drink);
        }

        // GET: Drink/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drink drink = await db.Query<Drink>().FirstAsync(d => d.ID == id);
            if (drink == null)
            {
                return HttpNotFound();
            }
            return View(drink);
        }

        // POST: Drink/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Drink drink = await db.FindAsync<Drink>(id);
            if (drink == null)
                return HttpNotFound("couldn't find the drink to remove");
            db.Remove(drink);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        public async Task<ActionResult> AddIngredient(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drink drink = await db.FindAsync<Drink>(id.GetValueOrDefault());
            if (drink == null)
            {
                return HttpNotFound();
            }
            var ingredients = db.Query<Ingredient>().OrderBy(q => q.Name).ToList();
            SelectList holdThis = new SelectList(ingredients, "ID", "Name", null);
            ViewData.Add("ingredientID", holdThis.AsEnumerable());

            return View(drink);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddIngredient(int id, int ingredientID)
        {
            Drink drink = await db.FindAsync<Drink>(id);
            if (drink == null)
                return HttpNotFound();

            Ingredient ingredient = db.Query<Ingredient>().First(i => i.ID == ingredientID);
            if (ingredient == null)
                return HttpNotFound();
            if (drink.DrinkIngredients == null)
                drink.DrinkIngredients = new HashSet<DrinkIngredient>();
            if (drink.DrinkIngredients.Any(di => di.IngredientID == ingredient.ID))
                    return new HttpStatusCodeResult(HttpStatusCode.Conflict);
            
            //conundrum. Either rewrite this to avoid using a feature so I can test it, or get rhinomocks (or something) involved.
            drink.DrinkIngredients.Add(new DrinkIngredient()
            {
                DrinkID = id,
                IngredientID = ingredient.ID
            });
            await db.SaveChangesAsync();

            return RedirectToAction("Edit/" + id);
        }
        [AllowAnonymous]
        public ActionResult DrinkIngredientDetails(int? id)
        {
            if (id == null)
                return HttpNotFound();
            DrinkIngredient di = db.Find<DrinkIngredient>(id.GetValueOrDefault());
            if (di == null)
                return HttpNotFound();

            var ingredient = db.Find<Ingredient>(di.IngredientID);
            if (ingredient == null)
                return HttpNotFound();
            ViewBag.ingredientName = ingredient.Name;

            return PartialView(di);
        }

        public ActionResult DrinkIngredientEdit(int? id)
        {
            if (id == null)
                return HttpNotFound();
            DrinkIngredient di = db.Find<DrinkIngredient>(id.GetValueOrDefault());
            if (di == null)
                return HttpNotFound();

            var ingredient = db.Find<Ingredient>(di.IngredientID);
            if (ingredient == null)
                return HttpNotFound();

            var ingredients = db.Query<Ingredient>().OrderBy(q => q.Name).ToList();
            SelectList holdThis = new SelectList(ingredients, "ID", "Name", di.IngredientID);
            ViewData.Add("DrinkIngredients[" + id + "].ingredientID", holdThis.AsEnumerable());
            
            return PartialView(di);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public Task<ActionResult> RemoveIngredient(int p1, int p2)
        {
            throw new System.NotImplementedException();
        }
    }
}

DrinkDatabase/Views/Drink/AddIngredient.cshtml
@{
    ViewBag.Title = "Add Ingredient";
}

<h2>Add Ingredient</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownList("ingredientID", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

DrinkDatabase/Views/Drink/Create.cshtml
@model DrinkDatabase.Models.Drink

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Drink</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Instructions, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Instructions, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Instructions, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Glass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Glass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Glass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DrinkDatabase/Views/Drink/Delete.cshtml
@model DrinkDatabase.Models.Drink

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Drink</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Glass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Glass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DrinkDatabase/Views/Drink/Details.cshtml
@model DrinkDatabase.Models.Drink
@using DrinkDatabase.Models;
@using System.Collections.Generic;

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>Ingredients</dt>
        <dd>
            @{
                @:<div class="row"><div class="col-md-4 di-header">Brand</div><div class="col-md-4 di-header">Name</div><div class="col-md-4 di-header">Amount</div></div>
                HashSet<DrinkIngredient> ings = new HashSet<DrinkIngredient>(
                    ((IEnumerable<DrinkIngredient>)ViewBag.DrinkIngredients)
                    .Where(i => i.DrinkID == Model.ID));
                if (ings.Count > 0)
                {
                    foreach (var item in ings)
                    {
                        @Html.Action("DrinkIngredientDetails", new { id = item.ID });
                    }
                }
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Instructions)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Instructions)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Glass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Glass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DrinkDatabase/Views/Drink/DrinkIngredientDetails.cshtml
@model DrinkDatabase.Models.DrinkIngredient
<div class="row">
    <div class="col-md-4">
        @Html.DisplayTextFor(model => model.Brand)
    </div>

    <div class="col-md-4">
        @ViewBag.ingredientName
    </div>

    <div class="col-md-4">
        @Html.DisplayTextFor(model => model.Amount)
    </div>
</div>

DrinkDatabase/Views/Drink/DrinkIngredientEdit.cshtml
@model DrinkDatabase.Models.DrinkIngredient
<div class="DrinkIngredient row">
    @Html.Hidden("DrinkIngredients.index", Model.ID)
    @Html.Hidden("DrinkIngredients[" + Model.ID + "].ID", Model.ID)
    @Html.Hidden("DrinkIngredients[" + Model.ID + "].DrinkID", Model.DrinkID)
    @Html.Hidden("DrinkIngredients[" + Model.ID + "].DrinkIngredientID", Model.ID)
    <div class="col-md-3">
        @Html.EditorFor(model => model.Brand, null, "DrinkIngredients[" + Model.ID + "].Brand", new { htmlAttributes = new { @class = "form-control autosave-delayed" } })
        @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
    </div>

    <div class="col-md-3">
        @Html.DropDownList("DrinkIngredients[" + Model.ID + "].ingredientID", null, htmlAttributes: new { @class = "form-control autosave-delayed-instant" })
    </div>

    <div class="col-md-3">
        @Html.EditorFor(model => model.Amount, null, "DrinkIngredients[" + Model.ID + "].Amount", new {htmlAttributes = new { @class = "form-control autosave-delayed" }})
        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-1">
        @{
            Html.Hidden("DeleteDrinkIngredients.index", Model.ID);
            var cbName="DeleteDrinkIngredients[" + Model.ID + "].Value";
            @:<input type="checkbox" name=@cbName />
        }
    </div>
</div>
@Scripts.Render("~/bundles/lessRedundant")

DrinkDatabase/Views/Drink/Edit.cshtml
@model DrinkDatabase.Models.Drink

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div id="editDrinkContainer">
    @Html.Partial("_EditableDrink", Model)
</div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ajax")
}

DrinkDatabase/Views/Drink/Index.cshtml
@model IEnumerable<DrinkDatabase.Models.Drink>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Instructions)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Glass)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notes)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Instructions)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Glass)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Notes)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

DrinkDatabase/Views/Drink/_EditableDrink.cshtml
@model DrinkDatabase.Models.Drink
@using (Html.BeginForm("Edit", "Drink", FormMethod.Post, new { id = "editDrinkForm" }))
{
<div class="form-horizontal">
    @Html.AntiForgeryToken()
    <h4>Drink</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control autosave-delayed" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @{
                HashSet<DrinkDatabase.Models.DrinkIngredient> ings = ViewBag.DrinkIngredients;
                <div class="row"><div class="col-md-3 di-header">Brand</div><div class="col-md-3 di-header">Name</div><div class="col-md-3 di-header">Amount</div><div class="col-md-1 di-header">Delete</div></div>
                foreach (var item in ings)
                {
                    @Html.Action("DrinkIngredientEdit", new { id = item.ID });
                }
            }
            <div class="row">@Html.ActionLink("add new", "AddIngredient", new { id = Model.ID })</div>
        </div>

    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Instructions, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instructions, new { htmlAttributes = new { @class = "form-control autosave-delayed" } })
            @Html.ValidationMessageFor(model => model.Instructions, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Glass, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Glass, new { htmlAttributes = new { @class = "form-control autosave-delayed" } })
            @Html.ValidationMessageFor(model => model.Glass, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control autosave-delayed" } })
            @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" id="editableDrinkSubmitButton" />
        </div>
    </div>
</div>
}